version: '3.3'
volumes:
  data:
services:
  desafio-meta:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=desafio-meta
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - desafio-meta
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1